export const ROLES = {
  ADMIN: 'ADMIN',
  OWNER: 'OWNER',
  RENTER: 'RENTER',
};

export const PERMISSIONS = {
  // Property Operations
  CREATE_PROPERTY: [ROLES.OWNER, ROLES.ADMIN],
  EDIT_PROPERTY: [ROLES.OWNER, ROLES.ADMIN],
  DELETE_PROPERTY: [ROLES.OWNER, ROLES.ADMIN],
  MODERATE_PROPERTY: [ROLES.ADMIN],

  // Booking & Visit Operations
  BOOK_VISIT: [ROLES.RENTER, ROLES.ADMIN],
  MANAGE_VISIT: [ROLES.OWNER, ROLES.ADMIN],

  // Payment Operations
  MAKE_PAYMENT: [ROLES.RENTER, ROLES.ADMIN],
  VIEW_REVENUE: [ROLES.OWNER, ROLES.ADMIN],

  // Review Operations
  WRITE_REVIEW: [ROLES.RENTER, ROLES.ADMIN],
  REPLY_TO_REVIEW: [ROLES.OWNER, ROLES.ADMIN],

  // Admin Dashboard Controls
  VIEW_SYSTEM_ANALYTICS: [ROLES.ADMIN],
  MANAGE_USER_ACCOUNTS: [ROLES.ADMIN],
  MODERATE_REVIEWS: [ROLES.ADMIN],
};

export default {
  ROLES,
  PERMISSIONS,
};
